from enum import StrEnum


class RequestActivityType(StrEnum):
    REQUEST_CREATED = "REQUEST_CREATED"
    REQUEST_UPDATED = "REQUEST_UPDATED"
    REQUEST_ASSIGNED = "REQUEST_ASSIGNED"
    REQUEST_COMMENT_ADDED = "REQUEST_COMMENT_ADDED"
    STATUS_CHANGED = "STATUS_CHANGED"
    COMMENT_ADDED = "COMMENT_ADDED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_VERIFIED_DATA_UPDATED = "DOCUMENT_VERIFIED_DATA_UPDATED"
    NOTE_ADDED = "NOTE_ADDED"
