from enum import StrEnum


class RequestActivityType(StrEnum):
    REQUEST_CREATED = "REQUEST_CREATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    COMMENT_ADDED = "COMMENT_ADDED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_VERIFIED_DATA_UPDATED = "DOCUMENT_VERIFIED_DATA_UPDATED"
    NOTE_ADDED = "NOTE_ADDED"
